/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;
       
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Daftar extends javax.swing.JFrame {
    private User user; 
    /**
     * Creates new form Daftar
     * @param user
     */         
    public Daftar(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_TipePasien = new javax.swing.ButtonGroup();
        lb_pendaftaran = new javax.swing.JLabel();
        lb_NamaPasien = new javax.swing.JLabel();
        lb_umur = new javax.swing.JLabel();
        lb_NIK = new javax.swing.JLabel();
        lb_TglLahir = new javax.swing.JLabel();
        lb_alamat = new javax.swing.JLabel();
        lb_TipePasien = new javax.swing.JLabel();
        lb_NoTlp = new javax.swing.JLabel();
        lb_poli = new javax.swing.JLabel();
        txt_NamaPasien = new javax.swing.JTextField();
        txt_umur = new javax.swing.JTextField();
        txt_NIK = new javax.swing.JTextField();
        txt_TglLahir = new javax.swing.JTextField();
        txt_NoTlp = new javax.swing.JTextField();
        sp_alamat = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        btn_daftar = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        txt_poli = new javax.swing.JComboBox<>();
        txt_pasienBiasa = new javax.swing.JRadioButton();
        txt_pasienBPJS = new javax.swing.JRadioButton();
        lb_user = new javax.swing.JLabel();
        lb_ktpBPJS = new javax.swing.JLabel();
        txt_ktpBPJS = new javax.swing.JTextField();
        lb_NamaPasien1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pendaftaran");
        setLocation(new java.awt.Point(500, 30));
        setName("frameDaftar"); // NOI18N

        lb_pendaftaran.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lb_pendaftaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_pendaftaran.setText("PENDAFTARAN");

        lb_NamaPasien.setText("Nama Pasien");

        lb_umur.setText("Umur");

        lb_NIK.setText("NIK");

        lb_TglLahir.setText("Tgl Lahir");

        lb_alamat.setText("Alamat");

        lb_TipePasien.setText("Tipe Pasien");

        lb_NoTlp.setText("No Telepon");

        lb_poli.setText("Poli");

        txt_NamaPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamaPasienActionPerformed(evt);
            }
        });

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        sp_alamat.setViewportView(txt_alamat);

        btn_daftar.setBackground(new java.awt.Color(23, 192, 237));
        btn_daftar.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar.setText("Daftar");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });

        btn_kembali.setBackground(new java.awt.Color(23, 192, 237));
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        txt_poli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jantung", "Mata", "Kulit", "Penyakit Dalam" }));

        btnG_TipePasien.add(txt_pasienBiasa);
        txt_pasienBiasa.setText("Biasa/Umum");

        btnG_TipePasien.add(txt_pasienBPJS);
        txt_pasienBPJS.setText("BPJS");
        txt_pasienBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pasienBPJSActionPerformed(evt);
            }
        });

        lb_user.setText(this.user.getUsername());

        lb_ktpBPJS.setText("No KTP/BPJS");

        txt_ktpBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ktpBPJSActionPerformed(evt);
            }
        });

        lb_NamaPasien1.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lb_umur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_NIK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_TglLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_TipePasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_poli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_NoTlp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_NamaPasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_NamaPasien1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_ktpBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_NamaPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txt_umur, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txt_NIK, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txt_TglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txt_NoTlp, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(sp_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txt_poli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ktpBPJS, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_pasienBiasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pasienBPJS))
                            .addComponent(lb_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lb_pendaftaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb_pendaftaran)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NamaPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_user))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_umur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_NoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_poli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_poli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_TipePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_pasienBiasa))
                    .addComponent(txt_pasienBPJS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ktpBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ktpBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_daftar)
                .addGap(18, 18, 18)
                .addComponent(btn_kembali)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        Login frameLogin = new Login();
                frameLogin.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        String nama_pasien = txt_NamaPasien.getText();
        String umur = txt_umur.getText();
        String tgl_lahir = txt_TglLahir.getText();
        String NIK = txt_NIK.getText();
        String alamat = txt_alamat.getText();
        String ktp_bpjs = txt_ktpBPJS.getText();
        String poli = txt_poli.getSelectedItem().toString();
        String no_tlp = txt_NoTlp.getText();
        boolean pasien_biasa = txt_pasienBiasa.isSelected();
        boolean pasien_bpjs = txt_pasienBPJS.isSelected();
        
        
        if (!"".equals(nama_pasien) && !"".equals(umur)&& !"".equals(NIK) && !"".equals(tgl_lahir) && !"".equals(no_tlp)&& !"".equals(poli)&& !"".equals(alamat)&& !"".equals(ktp_bpjs)){
            Pasien pasien = new Pasien(this.user.getUsername(),this.user.getPassword(),nama_pasien,umur,tgl_lahir,NIK,alamat,ktp_bpjs,poli,no_tlp);
            
            String tipe_pasien = null;
            if(txt_pasienBiasa.isSelected()) {
                 tipe_pasien = "Pasien Biasa";
            }else if (txt_pasienBPJS.isSelected()){
                 tipe_pasien = "Pasien BPJS";
            }
            
            Kartu_antrian kartu_antrian = new Kartu_antrian(1,tipe_pasien);
            //kartu_antrian.setNo_antrian(1);
            
            Kartu_antri frameAntrian = new Kartu_antri(pasien,kartu_antrian);
            frameAntrian.setVisible(true);
                    this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "isi semua data","ERROR", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btn_daftarActionPerformed

    private void txt_NamaPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamaPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NamaPasienActionPerformed

    private void txt_pasienBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pasienBPJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pasienBPJSActionPerformed

    private void txt_ktpBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ktpBPJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ktpBPJSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_TipePasien;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JLabel lb_NIK;
    private javax.swing.JLabel lb_NamaPasien;
    private javax.swing.JLabel lb_NamaPasien1;
    private javax.swing.JLabel lb_NoTlp;
    private javax.swing.JLabel lb_TglLahir;
    private javax.swing.JLabel lb_TipePasien;
    private javax.swing.JLabel lb_alamat;
    private javax.swing.JLabel lb_ktpBPJS;
    private javax.swing.JLabel lb_pendaftaran;
    private javax.swing.JLabel lb_poli;
    private javax.swing.JLabel lb_umur;
    private javax.swing.JLabel lb_user;
    private javax.swing.JScrollPane sp_alamat;
    private javax.swing.JTextField txt_NIK;
    private javax.swing.JTextField txt_NamaPasien;
    private javax.swing.JTextField txt_NoTlp;
    private javax.swing.JTextField txt_TglLahir;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_ktpBPJS;
    private javax.swing.JRadioButton txt_pasienBPJS;
    private javax.swing.JRadioButton txt_pasienBiasa;
    private javax.swing.JComboBox<String> txt_poli;
    private javax.swing.JTextField txt_umur;
    // End of variables declaration//GEN-END:variables
}
